# Generated by Django 6.0.4 on 2026-04-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='estimated_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
