# Generated by Django 6.0.4 on 2026-04-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cventry',
            name='skill',
        ),
        migrations.AddField(
            model_name='cventry',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
