# Generated by Django 6.0.4 on 2026-04-18 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('critical', 'Critical')], max_length=20)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended')], max_length=20)),
                ('correct_answer', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_sessions.learningsession')),
            ],
        ),
    ]
