# Generated by Django 6.0.4 on 2026-04-18 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('source', models.CharField(choices=[('learning', 'Learning'), ('manual', 'Manual')], default='learning', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
