# Generated by Django 6.0.4 on 2026-04-18 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('freelance', 'Freelance'), ('internship', 'Internship'), ('entry-level', 'Entry Level')], max_length=20)),
                ('skill_tags', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
